apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  parentRefs:
    - name: gateway-internal
      namespace: envoy-gateway
  hostnames:
    - "hv-test.qa.linkedbro.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gateway
          port: 18789
