apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  ingressClassName: nginx-internal
  rules:
    - host: hv-test.qa.linkedbro.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 18789
